version: "3.7"
services:
  db:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - backend
    volumes:
      - ${DB_DATA}:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    image: kinnaradigitalstudio/kecak-workflow:no-ssl-latest
    # build: ./web
    depends_on:
      - db
    environment:
      - JAVA_MEMORY=${WFLOW_JAVA_MEMORY}
    #links:
    #  # database is accessible from web by using hostname 'db'
    #  - "db:db"
    networks:
      - backend
    volumes:
      - ${WFLOW_DIR}:/usr/local/tomcat/wflow
    ports:
      # application port
      #- "8080:8080"

      # debugging port
      - "8000:8000"
    command : ["wait-for-it", "db:3306", "--", "/usr/local/tomcat/tomcat8.sh", "run"]
  proxy:
    image: kinnaradigitalstudio/kecak-proxy:no-ssl-latest
    depends_on:
      - web
      - db
    #links:
    #  - "web:web"
    networks:
      - backend
    ports:
      - "80:80"
    environment:
      - PROXY_HOST
      - PROXY_DEFAULT_PORT
      - PROXY_MAX_UPLOAD_SIZE
    command : ["wait-for-it", "web:8080", "--", "/usr/local/bin/start.sh"]
networks:
  backend:
