version: "3"
services:
  db:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ${DB_DATA}:/var/lib/mysql
  web:
    image: kinnaradigitalstudio/kecak-workflow:1.4.0
    # build: ./web
    depends_on:
      - db
    environment:
      - JAVA_MEMORY=${WFLOW_JAVA_MEMORY}
    links:
      # database is accessible from web by using hostname 'db'
      - "db:db"
    volumes:
      - ${WFLOW_DIR}:/usr/local/tomcat/wflow
    ports:
      # application port
      - "8080:8080"

      # debugging port
      - "8000:8000"
  proxy:
    image: kinnaradigitalstudio/kecak-proxy:no-ssl
    depends_on:
      - web
    links:
      - "web:web"
    ports:
      - "80:80"
    environment:
      - PROXY_HOST
      - PROXY_DEFAULT_PORT
      - PROXY_MAX_UPLOAD_SIZE
